inherit_from: .rubocop_todo.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRailsVersion: 7.0
  TargetRubyVersion: 3.0
  Exclude:
    - .git/**/*
    - .github/**/*
    - bin/**/*
    - gemfiles/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

Layout/LineLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false
